"""empty message

Revision ID: 071b26981293
Revises: 7cd1c19aad13
Create Date: 2019-02-21 15:11:23.977421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071b26981293'
down_revision = '7cd1c19aad13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'image')
    # ### end Alembic commands ###
