"""empty message

Revision ID: 7cd1c19aad13
Revises: 8a1c8ae54064
Create Date: 2019-02-21 12:48:25.290449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd1c19aad13'
down_revision = '8a1c8ae54064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('region', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'region')
    # ### end Alembic commands ###
